version: '3.9'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/app
    env_file:
    - .env    
    networks:
      - mongo-net

networks:
  mongo-net:
    external: True