version: "3"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1#4sa1B4Y
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongo-net
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    networks:
      - mongo-net
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1#4sa1B4Y
      ME_CONFIG_MONGODB_URL: mongodb://root:1#4sa1B4Y@mongo:27017/
    


  metabase:
    image: metabase/metabase
    restart: always
    ports:
      - 3000:3000
    networks:
      - mongo-net
    volumes:
      - metabase-data:/metabase.db
networks:
  mongo-net:
    name: mongo-net
volumes:
  mongodb-data:
    name: mongodb-data
  metabase-data:
    name: metabase-data

