version: '3.9'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/app
    env_file:
    - .env    
    networks:
      - mongo-net
    deploy:
        resources:
            limits:
              cpus: 1.00
              memory: 512M
            reservations:
              cpus: 0.50
              memory: 128M

networks:
  mongo-net:
    external: True